"""empty message

Revision ID: db387fd514dd
Revises: ccbe226b126c
Create Date: 2024-02-08 15:29:30.391305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db387fd514dd'
down_revision: Union[str, None] = 'ccbe226b126c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'pairs', ['symbol'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pairs', type_='unique')
    # ### end Alembic commands ###
