version: '3.8'
#
services:
  fastapi-docker:
    container_name: fastapi-docker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    depends_on:
      postgres-docker:
        condition: service_healthy
      nats-docker:
        condition: service_started
      redis-docker:
        condition: service_started

  nats-docker:
    image: nats:latest
    ports:
      - "4222:4222"

  redis-docker:
    image: "redis:latest"
    ports:
      - "6379:6379"

  postgres-docker:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: test_b_w
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
        interval: 5s
        timeout: 10s
        retries: 5
        start_period: 10s

volumes:
      postgres-data: